story4/urls.py
from django.urls import path
from . import views

app_name = 'story4'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('abilities/', views.abilities, name='abilities'),
    path('experiences/', views.experiences, name='experiences'),
    path('photograph/', views.photograph, name='photograph'),
    path('contact/', views.contact, name='contact'),
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.schedule, name='schedule'),
    path('/create', views.schedule_create, name='schedule_create'),
    path('clear/<int:id>/', views.schedule_delete, name='schedule_delete'),
]

storyPPW/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('schedule/',include('story5.urls') )
]

story4/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models
from datetime import datetime

# Create your models here.

CATEGORY_CHOICES = (
    ('kuliah','Kuliah'),
    ('compfest', 'Compfest'),
    ('bem', 'BEM'),
    ('others', 'Others'),
)


class Schedule(models.Model):

    activity = models.CharField(max_length=30)
    date = models.DateTimeField(default=datetime.now)
    time = models.TimeField()
    place = models.CharField(max_length=20)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)

    def __str__(self):
        return self.activity

story5/forms.py
from django import forms
from .models import Schedule


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['activity', 'date', 'time', 'place', 'category']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

story4/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def experiences(request):
    return render(request, 'experiences.html')

def abilities(request):
    return render(request, 'abilities.html')

def photograph(request):
    return render(request, 'photograph.html')

def profile(request):
    return render(request, 'profile.html')

def contact(request):
    return render(request, 'contact.html')

story5/views.py
from django.shortcuts import render, redirect
from .models import Schedule
from . import forms
from django.http import HttpResponse

def schedule(request):
    schedules = Schedule.objects.all().order_by('date')
    return render(request, 'schedule.html', {'schedules': schedules})

def schedule_create(request):
    if request.method == 'POST':
        form = forms.ScheduleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('story5:schedule')

    else:
        form = forms.ScheduleForm()
    return render(request, 'schedule_create.html', {'form': form})

def schedule_delete(request, id):
    if request.method == 'POST':
        Schedule.objects.filter(id=id).delete()
        return redirect('story5:schedule')
    else:
        return HttpResponse("GET/ not allowed")

story4/templates/abilities.html
{% load static %}
<html>

    <head>
        <title>Al Kwarizmi</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        ="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" 
        media="all" href="{% static 'css/styleStory3.css' %}"> 
        <link rel="icon" href="600px-OG_RB_Logo.png"> 
    </head>
    
    <nav style="background-color: black" class="navbar navbar-expand-lg navbar-light bg-light">
        <a href="{% url 'story4:index' %}"><img src="{% static 'images/AL.png' %}" class="img-fluid logo-al" alt="Responsive image"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="\profile\">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="\abilities\">Abilities</a>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="\experiences\">Experiences</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="\photograph\">Photographs</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="\contact\">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="\schedule\">Schedule</a>
            </li>
          </ul>
        </div>
      </nav>

    <body class="abilities">
        <section>
            <div></div>
                        <div id="judul">
                            <center><h1 style="font-size: 50px;"><strong>Abilities</strong></h1></center>
                        </div>
                        <div class="container-lagi">
                            <div class="item4">
                                    <div class="row">
                                            <div class="col" style="width:50%; text-align: center;">
                                                <h1>Skills</h1>
                                                <li>HTML</li>
                                                <li>Python</li>
                                                <li>CSS</li>
                                                <li>SQl</li>
                                                <li>Java</li>
                                            </div>
                                            <div class="col" style="padding-top: 17%">
                                            <img src="{% static 'images/Group 10.png' %}" class="bintang" >
                                            <img style="padding-top:18%" src="{% static 'images/Group 10.png' %}">
                                            <img style="padding-top:19%" src="{% static 'images/Group 10.png' %}">
                                            <img style="padding-top:21%" src="{% static 'images/Group 10.png' %}">
                                            <img style="padding-top:22%" src="{% static 'images/Group 10.png' %}">
                                            </div>
                                          </div>
                            </div>
                            <div class="item5" style="padding-top: 9%;">
                                    <div class="row">
                                            <div class="col" style="width:50%; text-align: center;">
                                                <li>Teamwork</li>
                                                <li>Microsoft Office</li>
                                                <li>Photoshop</li>
                                                <li>Ilustrator</li>
                                                <li>Premiere Pro</li>
                                            </div>
                                            <div class="col" style="padding-top: 6%">
                                            <img src="{% static 'images/Group 10.png' %}" class="bintang" >
                                            <img style="padding-top:15%;" src="{% static 'images/Group 10.png' %}">
                                            <img style="padding-top:24%;" src="{% static 'images/Group 10.png' %}">
                                            <img style="padding-top:20%;" src="{% static 'images/Group 10.png' %}">
                                            <img style="padding-top:20%;" src="{% static 'images/Group 10.png' %}">
                                            </div>
                                          </div>
                            </div>
                        </div>
        </section>
    </body>
</html>

story4/templates/contact.html
{% load static %}
<html>

    <head>
        <title>Al Kwarizmi</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        ="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" 
        media="all" href="{% static 'css/styleStory3.css' %}"> 
        <link rel="icon" href="600px-OG_RB_Logo.png"> 


    </head>
    
    <nav style="background-color: black" class="navbar navbar-expand-lg navbar-light bg-light">
      <a href="{% url 'story4:index' %}"><img src="{% static 'images/AL.png' %}" class="img-fluid logo-al" alt="Responsive image"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="\profile\">Profile</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="\abilities\">Abilities</a>
            </li>
          <li class="nav-item">
            <a class="nav-link" href="\experiences\">Experiences</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="\photograph\">Photographs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="\contact\">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="\schedule\">Schedule</a>
          </li>
        </ul>
      </div>
    </nav>
    
    <body class="contact" style="background-color: white">
        <section>
                        <div id="judul">
                            <center><h1 style="font-size: 50px;"><strong>Contact</strong></h1></center>
                        </div>
                        <div style=" padding-top: 4%; text-align: center" class="container">
                                <div style="margin-top: 5px " class="row">
                                  <div class="col contact-img">
                                    <a href="http://www.instagram.com/alkwrzm"><img style="width: 12%;" src="{% static 'images/instagram(1).png' %}"><span class="right-content">instagram.com/alkwrzm</span></a>
                                  </div>
                                  <div class="col contact-img">
                                    <a href="http://www.twitter.com/alkwrzmda"><img style="width: 15%; padding-left: 5%;" src="{% static 'images/twitter(1).png' %}"><span class="right-content">twitter.com/alkwrzmda</span></a>
                                  </div>
                                  <div class="w-100"></div>
                                  <div class="col contact-img">
                                    <a href="http://www.linkedin.com/in/mohammed-al"><img style="width: 10%; margin-left: 10%;" src="{% static 'images/linkedin(1).png' %}"><span class="right-content">linkedin.com/in/mohammed-al</span></a>
                                  </div>
                                  <div class="col contact-img">
                                   <a><img style="width: 15%; padding-left: 5%" src="{% static 'images/email(1).png' %}"><span class="images/right-content">mohammed.al@ui.ac.id</span></a>
                                  </div>
                                </div>
                        </div>  
        </section>
    </body>
</html>

story4/templates/experiences.html
{% load static %}   
<html>

    <head>
        <title>Al Kwarizmi</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        ="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" 
        media="all" href="{% static 'css/styleStory3.css' %}"> 
        <link rel="icon" href="600px-OG_RB_Logo.png"> 
    </head>
    
    <nav style="background-color: black" class="navbar navbar-expand-lg navbar-light bg-light">
      <a href="{% url 'story4:index' %}"><img src="{% static 'images/AL.png' %}" class="img-fluid logo-al" alt="Responsive image"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="\profile\">Profile</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="\abilities\">Abilities</a>
            </li>
          <li class="nav-item">
            <a class="nav-link" href="\experiences\">Experiences</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="\photograph\">Photographs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="\contact\">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="\schedule\">Schedule</a>
          </li>
        </ul>
      </div>
    </nav>

    <body class="experience" style="background-color: white">
        <section>
            <div></div>
                        <div id="judul">
                            <center><h1 style="font-size: 50px;"><strong>Experience</strong></h1></center>
                        </div>
                        <div class="container-lagi">
                            <div class="item4 education" style="text-align: center">
                                <div style="line-height: 2">
                                    <h1>Education</h1>
                                    <strong>University of Indonesia</strong><br>
                                    2018 - Present<br>
                                    <strong>38 Jakarta Senior High School</strong><br>
                                    2015 - 2018<br>
                                    <strong>Al-Madinah Junior High School</strong><br>
                                    2012 - 2015<br>
                                </div>
                            </div>
                            <div class="item5 organization" style="text-align: center">
                                <div style="line-height: 2">
                                    <h1>Organization</h1>
                                <strong>Compfest 11<br>
                                    VPIC Equipment and Security
                                    </strong><br>
                                    2018 - Present<br>
                                <strong>Warung Pintar<br>
                                    Researcher Volunteer</strong><br>
                                    July 2019 - Agustus 2019<br>
                                <strong>BEM Fasilkom UI<br>
                                    Staff of Human Resources Development Bureau</strong><br>
                                    June 2019 - Present<br>
                                </div>
                            </div>
                        </div>
        </section>    
    </body>
</html>

<!-- <header class="container-header">
    <div class="header-kiri">
            <img src="{% static 'images/AL.png' %}" class="img-fluid logo-al" alt="Responsive image">
    </div>
    <div class="header-kanan">
            <a href="/"><img class="logo-rumah" src="{% static 'images/home.png' %}"></a>
    </div>
</header> -->

story4/templates/index.html
{% load static %}
<html>

    <head>
        <title>Al Kwarizmi</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        ="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" 
        media="all" href="{% static 'css/styleStory3.css' %}"> 
        <link rel="icon" href="600px-OG_RB_Logo.png"> 
    </head>
    
    <nav style="background-color: black" class="navbar navbar-expand-lg navbar-light bg-light">
      <a href="{% url 'story4:index' %}"><img src="{% static 'images/AL.png' %}" class="img-fluid logo-al" alt="Responsive image"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="\profile\">Profile</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="\abilities\">Abilities</a>
            </li>
          <li class="nav-item">
            <a class="nav-link" href="\experiences\">Experiences</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="\photograph\">Photographs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="\contact\">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="\schedule\">Schedule</a>
          </li>
        </ul>
      </div>
    </nav>
    
    <body class="index" style="background-color: #6384B3">
        <section>
            <div class="grid-container">
                    <div class="item2">
                        <h1 style="text-shadow: black; font-style: italic; font-family: santisa one; font-display: block; text-align: center; font-size: 160px;">
                        AL<br>KWARIZMI
                        </h1>
                    </div>
                </div>
        </section>
    </body>
</html>

story4/templates/photograph.html
{% load static %}
<html>

    <head>
        <title>Al Kwarizmi</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        ="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" 
        media="all" href="{% static 'css/styleStory3.css' %}"> 
        <link rel="icon" href="600px-OG_RB_Logo.png"> 
    </head>
    
    <nav style="background-color: black" class="navbar navbar-expand-lg navbar-light bg-light">
      <a href="{% url 'story4:index' %}"><img src="{% static 'images/AL.png' %}" class="img-fluid logo-al" alt="Responsive image"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="\profile\">Profile</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="\abilities\">Abilities</a>
            </li>
          <li class="nav-item">
            <a class="nav-link" href="\experiences\">Experiences</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="\photograph\">Photographs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="\contact\">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="\schedule\">Schedule</a>
          </li>
        </ul>
      </div>
    </nav>

    <body style="background-color: #E6F0B6 " class="photograph">
        <section>
                        <div id="judul">
                            <center><h1 style="font-size: 50px;"><strong>Photographs</strong></h1></center>
                        </div>
                        <div class="row">
                            <div class="col">
                            <img style="width: 40%" src="{% static 'images/kecil1.jpg' %}" class="img-fluid" alt="Responsive image">
                            </div>
                            <div class="col">
                             <img style="width: 50%" src="{% static 'images/frrd.jpg' %}" class="img-fluid" alt="Responsive image">
                            </div>
                          </div>
                          <div class="row">
                            <div class="col">
                                    <img style="width: 90%" src="{% static 'images/wisuda.jpg' %}" class="img-fluid" alt="Responsive image">
                            </div>
                            <div class="col">
                                    <img style="width: 80%" src="{% static 'images/turing.jpg' %}" class="img-fluid" alt="Responsive image">
                            </div>
                            <div style="padding-top: 2%" class="col">
                                    <img style="width: 90%" src="{% static 'images/lbr.jpg' %}" class="img-fluid" alt="Responsive image">
                            </div>
                          </div>
        </section>    
    </body>
</html>

story4/templates/profile.html
{% load static %}
<html>

    <head>
        <title>Al Kwarizmi</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        ="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" 
        media="all" href="{% static 'css/styleStory3.css' %}"> 
        <link rel="icon" href="600px-OG_RB_Logo.png"> 
    </head>

    <nav style="background-color: black" class="navbar navbar-expand-lg navbar-light bg-light">
      <a href="{% url 'story4:index' %}"><img src="{% static 'images/AL.png' %}" class="img-fluid logo-al" alt="Responsive image"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="\profile\">Profile</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="\abilities\">Abilities</a>
            </li>
          <li class="nav-item">
            <a class="nav-link" href="\experiences\">Experiences</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="\photograph\">Photographs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="\contact\">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="\schedule\">Schedule</a>
          </li>
        </ul>
      </div>
    </nav>


    <body class="profile" style="background-color: white;">
        <section>
                    <div id="judul">
                    <center><h1 style="font-size: 50px;"><strong>Profile</strong></h1></center>
                    </div>
                    <div style=" padding-top: 5%" class="row">
                            <div style="padding-right: 0%; padding-left: 10%" class="col">
                            <center><h1 style="width: 90%">About Me</h1></center>
                              <div style="width: 80%; float:right; ">Al is an Information System 
                                student at the Computer Science 
                                Faculty of Universitas Indonesia 
                                who have an interest in business,
                                IT, and databases. Able to work in
                                teams and under pressure. A hard 
                                working and easy-motivated person. 
                                Really like to try new things, organize, 
                                analyze, and make relations with people. Currently, 
                                has special interests in web development and data analytics.</div>
                            </div>
                            <div style="align-items: center; padding-left: 5%" class="col">
                              <img style=" width: 200px; height: 200px; border-radius: 70%; border-image-width: 2%" src="{% static 'images/foto-baju-merah.png' %}">
                              <p style="padding-left: 3%; padding-top: 25%">Excited to see my <strong>RESUME?</strong></p>
                              <a style="padding-left: 15%" href="https://drive.google.com/open?id=16EJfAXy9YR2g26zQ2kj5LQkgJxEWQnXI"><img style="width: 124px" src="{% static 'images/lukhir.png' %}"></a>
                            </div>
                            <div class="col">
                              <h1>Details</h1>
                                <strong>Name:</strong><br>
                                Mohammed Al Kwarizmi<br>
                                <strong>Age:</strong><br>
                                19 y.o<br>
                               <strong>Location:</strong><br>
                               Bogor, Java, Indonesia<br>
                            </div>
                    </div>
                </div>
        </section>
    </body>
</html>

story5/templates/schedule.html
<html>

    <head>
        <title>Al Kwarizmi</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        ="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" 
        media="all" href="styleStory3.css"> 
        <link rel="icon" href="600px-OG_RB_Logo.png"> 


    </head>
    
    
    <body class="listActivities" style="background-color: white">
      <header class="container-header">
        <a href="{% url 'story4:index' %}"><button style="margin: 2% 2% 2% 2%" type="button" class="btn btn-dark">HOME</button></a>
      </header>
        <section>
            <div id="judul">
                <center><h1 style="font-size: 50px;"><strong>List Activities</strong></h1></center>
            </div>
            <div class="col-sm-4"><h1>MY SCHEDULE.</h1>
                <div class="article">
                    <a href="\activities\"></a>
                    <div class="article">
                        <div class="row">
                            {% for schedule in schedules %}
                                <div class="col-sm-4 text-center">
                                    <h2>{{ schedule.activity }}</h2>
                                    <p>{{ schedule.date.date }}</p>
                                    <p>{{ schedule.time}}</p>
                                    <p>{{ schedule.place }}</p>
                                    <p>{{ schedule.category }}</p>
                                    <div class ='form-group'>
                                        <form action="/schedule/clear/{{ schedule.id }}/" method="POST">
                                            {% csrf_token %}
                                            <button class="btn btn-danger" type="submit">Delete</button>
                                        </form>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class = 'col-md-12'>
                        <a href="{% url 'story5:schedule_create' %}"><button type="button" class= "btn btn-secondary btn-lg btn-sm">Create</button></a>
                </div>        
            </div>
        </section>
    </body>
</html>

story5/templates/schedule_create.html
<html>

    <head>
        <title>Al Kwarizmi</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        ="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" 
        media="all" href="styleStory3.css"> 
        <link rel="icon" href="600px-OG_RB_Logo.png"> 


    </head>
    

    <body class="activities" style="background-color: white">
      <header class="container-header">
        <a href="{% url 'story4:index' %}"><button style="margin: 2% 2% 2% 2%" type="button" class="btn btn-dark">HOME</button></a>
      </header>
        <section>
            <div id="judul">
                <center><h1 style="font-size: 50px;"><strong>Create Activities</strong></h1></center>
            </div>
            <form class="css" action="{% url 'story5:schedule_create' %}" method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-sm-1"></div>
                    <div class="form-group col-sm-10">
                        {% for fields in form %}
                            {{ fields.label_tag }}
                            <br>
                            {{ fields }}
                        {% endfor %}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-sm-1"></div>
                    <input type="submit" class="btn btn-primary float-right" value="Add">
                </form>  
        </section>
    </body>
</html>